// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQVP-oTs9H0GH9D-zKw6aYzjDEnlZcjcg',
    appId: '1:240571866446:web:43360c5e28810922f4121f',
    messagingSenderId: '240571866446',
    projectId: 'flutter-ai-playground-b188b',
    authDomain: 'flutter-ai-playground-b188b.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-b188b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsYnOnzX0JYGVsWY9zAiBU9bNsL2fA9T4',
    appId: '1:240571866446:android:dda6b905f909c210f4121f',
    messagingSenderId: '240571866446',
    projectId: 'flutter-ai-playground-b188b',
    storageBucket: 'flutter-ai-playground-b188b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNjRGOSL-vp5tYfOy6k_4iFXXsKfP9WY',
    appId: '1:240571866446:ios:3d86e8be3329a06df4121f',
    messagingSenderId: '240571866446',
    projectId: 'flutter-ai-playground-b188b',
    storageBucket: 'flutter-ai-playground-b188b.firebasestorage.app',
    iosBundleId: 'com.vantag.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvNjRGOSL-vp5tYfOy6k_4iFXXsKfP9WY',
    appId: '1:240571866446:ios:0e7af21024f900a4f4121f',
    messagingSenderId: '240571866446',
    projectId: 'flutter-ai-playground-b188b',
    storageBucket: 'flutter-ai-playground-b188b.firebasestorage.app',
    iosBundleId: 'com.example.mmrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQVP-oTs9H0GH9D-zKw6aYzjDEnlZcjcg',
    appId: '1:240571866446:web:d63cda7c2c20d8bbf4121f',
    messagingSenderId: '240571866446',
    projectId: 'flutter-ai-playground-b188b',
    authDomain: 'flutter-ai-playground-b188b.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-b188b.firebasestorage.app',
  );
}
